/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGisRouteImport } from './routes/_authenticated/gis'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedRecordsIndexRouteImport } from './routes/_authenticated/records.index'
import { Route as AuthenticatedRecordsIdRouteImport } from './routes/_authenticated/records.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGisRoute = AuthenticatedGisRouteImport.update({
  id: '/_authenticated/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/_authenticated/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/_authenticated/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsIndexRoute =
  AuthenticatedRecordsIndexRouteImport.update({
    id: '/_authenticated/records/',
    path: '/records/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecordsIdRoute = AuthenticatedRecordsIdRouteImport.update({
  id: '/_authenticated/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gis': typeof AuthenticatedGisRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records/': typeof AuthenticatedRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gis': typeof AuthenticatedGisRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records': typeof AuthenticatedRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gis': typeof AuthenticatedGisRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/records/$id': typeof AuthenticatedRecordsIdRoute
  '/_authenticated/records/': typeof AuthenticatedRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/gis'
    | '/queue'
    | '/upload'
    | '/records/$id'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/gis'
    | '/queue'
    | '/upload'
    | '/records/$id'
    | '/records'
  id:
    | '__root__'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/gis'
    | '/_authenticated/queue'
    | '/_authenticated/upload'
    | '/_authenticated/records/$id'
    | '/_authenticated/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGisRoute: typeof AuthenticatedGisRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedRecordsIdRoute: typeof AuthenticatedRecordsIdRoute
  AuthenticatedRecordsIndexRoute: typeof AuthenticatedRecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gis': {
      id: '/_authenticated/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AuthenticatedGisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records/': {
      id: '/_authenticated/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AuthenticatedRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records/$id': {
      id: '/_authenticated/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AuthenticatedRecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGisRoute: AuthenticatedGisRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedRecordsIdRoute: AuthenticatedRecordsIdRoute,
  AuthenticatedRecordsIndexRoute: AuthenticatedRecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
